# Generated by Django 5.1.4 on 2025-01-07 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayertime',
            name='sunrise',
            field=models.TimeField(default=datetime.datetime(2025, 1, 7, 9, 41, 19, 527754, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='sso_user_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
