# Generated by Django 5.1.4 on 2025-01-07 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_prayertime_sunrise_alter_user_sso_user_id'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.file'),
        ),
    ]
