# Generated by Django 5.1.4 on 2025-02-20 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_slider_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayertime',
            name='imsak',
            field=models.TimeField(default=datetime.time(10, 11, 13, 800063)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prayertime',
            name='midight',
            field=models.TimeField(default=datetime.time(10, 11, 23, 237361)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prayertime',
            name='sunset',
            field=models.TimeField(default=datetime.time(10, 11, 29, 661319)),
            preserve_default=False,
        ),
    ]
