# Generated by Django 5.1.4 on 2025-03-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_masjidconfiguration_slide_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masjidconfiguration',
            name='adzan_popup_duration',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='masjidconfiguration',
            name='iqomah_popup_duration',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='masjidconfiguration',
            name='khutbah_popup_duration',
            field=models.PositiveIntegerField(default=2700),
        ),
        migrations.AlterField(
            model_name='masjidconfiguration',
            name='slide_duration',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='masjidconfiguration',
            name='slide_scroll_duration',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
